과제/ch3/my_first_pjt/my_first_pjt/articles/urls.py
from django.urls import path
from . import views


app_name = "articles"
urlpatterns = [
    path("", views.articles, name="articles"),
    path("create/", views.create, name="create"),
    path("<int:pk>/", views.article_detail, name="article_detail"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/comments/", views.comment_create, name="comment_create"),
    path("<int:pk>/comments/<int:comment_pk>/delete/", views.comment_delete, name="comment_delete"),
    path("<int:pk>/like/", views.like, name="like"),

    path("index/", views.index, name="index"),
    path("data_throw/", views.data_throw, name= "data_throw"),
    path("data_catch/", views.data_catch, name= "data_catch"),
]

과제/ch3/my_first_pjt/my_first_pjt/my_first_pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from articles import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("index/", views.index, name="index"),
    path("articles/", include("articles.urls")),
    path("users/", include("users.urls")),
    path("accounts/", include("accounts.urls")),
    

    path("data_throw/", views.data_throw, name= "data_throw"),
    path("data_catch/", views.data_catch, name= "data_catch"),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

과제/ch3/my_first_pjt/my_first_pjt/urls.py
from django.contrib import admin
from django.urls import path
from articles import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("articles/", views.articles, name="articles"),
    path("data_throw/", views.data_throw, name="data_throw"),
    path("hello/", views.hello),
]

과제/ch3/my_first_pjt/my_first_pjt/users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path("", views.users, name="users"),
    path("profile/<str:username>/", views.profile, name="profile"),
    path("<int:user_id>/follow/", views.follow,name="follow"),
    ]

과제/ch3/my_first_pjt/my_first_pjt/users/models.py
from django.db import models

# Create your models here.

과제/ch3/my_first_pjt/my_first_pjt/users/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST
from django.shortcuts import get_object_or_404
from django.contrib.auth import get_user_model

def users(request):
	return render(request, "users/users.html")

def profile(request, username):
    member = get_object_or_404(get_user_model(), username=username)
    context = {"member": member,}
    return render(request,"users/profile.html", context)

@require_POST
def follow(request, user_id):
    if request.user.is_authenticated:
        member = get_object_or_404(get_user_model(), pk=user_id)
        if member!= request.user:
            if member.followers.filter(pk=request.user.pk).exists():
                member.followers.remove(request.user)
            else:
                member.followers.add(request.user)
        return redirect("users:profile", username=member.username)
    else:
        return redirect("accounts:login")
         

과제/ch3/my_first_pjt/my_first_pjt/users/templates/users/profile.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ member.username }} profile page</h1>

    <div>
        <h3> username : {{member.username}}</h3>

        {% if request.user != member %}
            <form action="{% url "users:follow" member.pk %}" method="POST">
                {% csrf_token %}
                {% if request.user in member.followers.all %}
                    <input type="submit" value="언팔로우">
                {% else %}
                    <input type="submit" value="팔로우">
                {% endif %}
            </form>
        {% endif %}
    </div> 

    <a href="/index/">INDEX로 돌아가기</a> 

{% endblock content%}

과제/ch3/my_first_pjt/my_first_pjt/users/templates/users/users.html
{% extends 'base.html' %}

{% block content %}
<h1>Users Page</h1>
<a href="{% url 'articles:index' %}">INDEX로 가기</a>
{% endblock %}