과제/ch3/my_first_pjt/my_first_pjt/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("signup/", views.signup, name="signup"),
    path("delete/", views.delete, name="delete"),
    path("update/", views.update, name="update"),
    path("password/", views.change_password, name="change_password"),
]

과제/ch3/my_first_pjt/my_first_pjt/my_first_pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from articles import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("index/", views.index, name="index"),
    path("articles/", include("articles.urls")),
    path("users/", include("users.urls")),
    path("accounts/", include("accounts.urls")),
    

    path("data_throw/", views.data_throw, name= "data_throw"),
    path("data_catch/", views.data_catch, name= "data_catch"),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

과제/ch3/my_first_pjt/my_first_pjt/urls.py
from django.contrib import admin
from django.urls import path
from articles import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("articles/", views.articles, name="articles"),
    path("data_throw/", views.data_throw, name="data_throw"),
    path("hello/", views.hello),
]

과제/ch3/my_first_pjt/my_first_pjt/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel = "stylesheet" href = "{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">    <link rel="stylesheet" href="{% static "css/style.css" %} ">
    <script src="https://kit.fontawesome.com/faa96354b3.js" crossorigin="anonymous"></script>
    <title>My First Django PJT</title>
  
    {% block head %}{% endblock head%}
  </head>
  <body>


    <div class="navbar">
      {% if request.user.is_authenticated %}
      <h3>hello, {{ request.user.username }}</h3>
      <form action="{% url 'accounts:logout' %}" method="post">
        {%csrf_token%}
        <input type="submit" value="로그아웃"></input>
      </form>

      <a href="{% url 'accounts:update' %}">회원정보수정</a>

      <form action="{% url 'accounts:delete' %}" method="post">
        {%csrf_token%}  
        <input type="submit" value="회원탈퇴"></input>
      </form>

      {% else %}
        <a href="{% url 'accounts:login' %}">로그인</a>
        <a href="{% url 'accounts:signup' %}">회원가입</a>
      {% endif %}
    </div>

    <div class="container">
      {%block content%}
      {%endblock content%}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    
  </body>
</html>